airportcars/urls.py
from django.urls import path
from airportcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='airportcars'

urlpatterns = [
    path('bookairportcar/',views.bookairportcar,name='bookairportcar'),
    path('book_a_car/(<int:air_id>)',views.book_a_car,name='book_a_car'),
    path('airportcars_history/',views.tourists_view_history,name='airportcars_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')

]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmsproject/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('accounts.urls')),
    path('rentedcars/',include('rentedcars.urls')),
    path('taxis/',include('taxis.urls')),
    path('contacts/',include('emergencycontacts.urls')),
    path('tourist/',include('touristcars.urls')),
    path('weddingcar/',include('weddingcars.urls')),
    path('airportcars/',include('airportcars.urls')),
    path('notifications/',include('notifications.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taxis/urls.py
from django.urls import path
from taxis import views

app_name='taxis'

urlpatterns = [
    path('booktaxi/',views.booktaxi,name='booktaxi'),
    path('avail_taxi/',views.avail_taxi,name='avail_taxi'),
    path('accept_taxi/(<int:accept_id>)',views.accept_taxi,name='accept_taxi'),
    path('your_trip/',views.your_trip,name='your_trip'),
    path('endtrip/(<int:end_id>)',views.endtrip,name='endtrip'),
    # path('all_trips/',views.all_trips,name='all_trips'),
    path('book_driver/',views.book_driver,name='book_driver'),
    path('book_d/(<int:driver_id>)',views.book_d,name='book_d'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map'),
    path('taxi_view_history/',views.taxi_view_history,name='taxi_view_history'),

]

touristcars/urls.py
from django.urls import path
from touristcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='touristcars'

urlpatterns = [
    path('booktour/',views.booktour,name='booktour'),
    path('booktourcar/(<int:tour_id>)',views.booktourcar,name='booktourcar'),
    path('touristcars_history/',views.tourists_view_history,name='touristcars_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

airportcars/models.py
from django.db import models
from accounts.models import *

# Create your models here.
class AirportCar(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    car_name = models.CharField(max_length=50)
    car_photo = models.ImageField(upload_to='images/airport')
    price = models.IntegerField()
    is_booked = models.BooleanField()
    from_airport = models.BooleanField()

    class Meta:
        indexes = [
            models.Index(fields = ['from_airport','is_booked',]),
        ]

class BookedAirportCar(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    user_booked = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)
    airport_car = models.ForeignKey(AirportCar,on_delete=models.CASCADE)
    date = models.DateField()

airportcars/views.py
from django.shortcuts import render,redirect
from accounts.models import *
from airportcars.models import *
from notifications.models import *

from geopy.geocoders import Nominatim
from django.utils import timezone


def bookairportcar(request):
    u=UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        for key in request.POST.items():
            if key[0] == 'from_airport':
                cars=AirportCar.objects.raw("CALL Getfromairport()")
                # cars=AirportCar.objects.filter(from_airport=True,is_booked=False)
            if key[0] == 'to_airport':
                cars=AirportCar.objects.raw("CALL Gettoairport()")
                # cars=AirportCar.objects.filter(from_airport=False,is_booked=False)
        return render(request,'airportcars/display.html',{'cars':cars})
    return redirect('accounts:home')


def book_a_car(request,air_id):
    u=UserProfile.objects.get(user=request.user)
    item = AirportCar.objects.get(pk = air_id)
    item.is_booked=True
    item.save()
    geolocator = Nominatim()
    location = request.POST.get('location')
    if item.from_airport == True:
        BookedAirportCar.objects.create(user_booked=u,from_location='Chennai International Airport (MAA), GST Rd, Meenambakkam, Chennai, Tamil Nadu',to_location=location,airport_car=item,date=timezone.now().date())
    elif item.from_airport == False:
        BookedAirportCar.objects.create(user_booked=u,from_location=location,to_location='Chennai International Airport (MAA), GST Rd, Meenambakkam, Chennai, Tamil Nadu',airport_car=item,date=timezone.now().date())
        NotificationList.objects.create(message='airport service car is booked to airport',read=False,user=u)
    return redirect('airportcars:bookairportcar')


def display_map(request,map_id):
    u=UserProfile.objects.get(user=request.user)
    trip = BookedAirportCar.objects.get(pk = map_id)
    return render(request,'airportcars/each_histroy.html',{'trip':trip})


def tourists_view_history(request):
    u=UserProfile.objects.get(user=request.user)
    all_trips = BookedAirportCar.objects.all()
    return render(request,'airportcars/airportcars_history.html',{'all_trips':all_trips,'u':u})

airportcars/templates/airportcars/airportcars_history.html
{% extends 'index.html' %}
{% load static %}

{% block body_block %}
<style>
    .card{
        margin: 1rem;
        padding: 10px;
        width: 200px;
        display: inline-block;
    }
    .image{
        background-image: url("{% static 'images/banner2.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }
    /* a{
        font-family: poppins;
        font-size: 18px;
    } */
</style>
<div class="image" style="width:1530px;height:300px;"><div style="color: white;font-size: 50px;font-family: poppins;position: absolute;left:35%;top:30%">Airport Cabs History</div></div>


{% for item in all_trips %}
<div class="card" style="width: 22rem;">
    <div class="card-body">
      {% if item.airport_car.from_airport == False %}
        <h4>Booked from airport</h4>
      {% elif item.airport_car.from_airport %}
        <h4>Booked to airport</h4>
      {% endif %}<br>
        <b>From Location:</b> {{ item.from_location }}<br>
        <b>To Location:</b> {{ item.to_location }}<br>
        <b>Date:</b> {{ item.date }}<br>
        <br>
        <a class="btn btn-primary" href="{% url 'airportcars:display_map' item.auto_increment_id %}" role="button">View More</a>

    </div>
</div>

<!-- <form id="calculate-route" name="calculate-route" action="{% url 'taxis:display_map' item.auto_increment_id %}" method="POST">
  {%csrf_token%}
    <input type="hidden" id="from" name="from"  value="{{ item.booking_Details.car_location }}" placeholder="Type an address"   />
  <br>

  <input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{ item.booking_Details.to_location }}"  />
<input type="submit" /> -->
{% endfor %}


{% endblock body_block %}

airportcars/templates/airportcars/display.html
{% extends 'index.html' %}
{% load static %}
{% block slidecss %}
<style>


      <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
      <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">



      .car{
            font-family: "Times New Roman", Times, serif;
            font-size: 20px;
      }
  header {
    position: relative;
    text-align: center;
    height: 30vh;
    background: linear-gradient(to right, #69bcf4, #30cc8b);
    color: #fff;
  }
  header h1 {
    padding-top: 20px;
    font-size: 3em;
    font-family: "Times New Roman", Times, serif;

  }
   header span.animated {
    position: absolute;
    margin: auto;
    right: 0;
    left: 0;
    bottom: 20px;
    height: 4px;
    width: 4px;
    border-radius: 2px;
    background: #fff;
    animation-duration: 2.5s;
    animation-iteration-count: infinite;
  }

  header span::before,
  header span::after {
    position: absolute;
    top: -23px;
    content: "";
    height: 30px;
    width: 4px;
    border-radius: 2px;
    background: #fff;
  }

  header span::before {
    left: -10px;
    transform:         rotate(-45deg);
  }

  header span::after {
    right: -10px;
    transform:         rotate(45deg);
  }

  .form{
      background-color: #fefefe;
      margin: 4% auto 15% auto;
      border: 1px solid #888;
      width: 500px;
      padding-bottom: 30px;
  }
  .modal {
      display:none;
      z-index: 1;
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgba(0,0,0,0.4);
  }
  .close {
      position: absolute;
      right: 25px;
      top: 0;
      color: #000;
      font-size: 35px;
      font-weight: bold;
  }
  .close:hover,.close:focus {
      color: #57cbcc;
      cursor: pointer;
  }
  input[type=text]{
      position: center;
      padding: 12px 20px;
      margin: 8px 26px;
      display: inline-block;
      border-radius: 10%;
      border: 1px solid #ccc;
      box-sizing: border-box;
      font-size:16px;
  }
  input[type=number]{
      position: center;
      padding: 12px 20px;
      margin: 8px 26px;
      display: inline-block;
      border-radius: 10%;
      border: 1px solid #ccc;
      box-sizing: border-box;
      font-size:16px;
  }

</style>
{% endblock slidecss %}

{% block body_block %}

<header style="width:100%">
    <h1 class="animated bounceInDown">Get Airport Cab</h1>
    <i class=" medium material-icons">airport_services</i>
  <span class="animated bounce"></span>
</header>

<div class="row" style="padding-top: 30px;padding-left:180px;">
{% for item in cars %}
<div style="display:inline-block;">
<div style="display:inline-block;">
  <div style="padding-left:30px;padding-top:30px;width:350px;height:500px">
    <div class="shadow" style="600px;height:480px;">
      <div class="card-image">
        <img class="responsive-img" src="{{item.car_photo.url}}" style="height:300px;width:100%;">
      </div>
      <div class="card-action" style="padding-left:70px;">
          <p class="car"><b>Car Name:</b>&nbsp;&nbsp;{{item.car_name}}</p>
          <p class="car"><b>Price:</b>&nbsp;&nbsp;Rs.{{item.price}}</p>
          <!-- {% if item.is_booked == False %}
            <th scope="row" style="font-weight: 600">
              Booked:&nbsp;&nbsp;<i class="fa fa-circle" style="color: red"></i>&nbsp;{{ item.is_booked }}</th>
              {% elif item.is_booked %}
              <th scope="row" style="font-weight: 600">
                Booked:<i class="fa fa-circle" style="color: green"></i>&nbsp;{{ item.is_booked }}</th>
          {% endif %}<br> -->

          <button onclick="document.getElementById('modal-wrapper').style.display='block'" class="btn btn-primary book_a" style="background-color:#57cbcc">Book a cab</button>
          <div id="modal-wrapper" class="modal">
              <form class="form" method="POST" action="{% url 'airportcars:book_a_car' item.auto_increment_id %}">
                  <div>
                      <span onclick="document.getElementById('modal-wrapper').style.display='none'" class="close" title="Close PopUp">&times;</span>
                  </div>
                  <div class="container">
                    <h3 style="color:#18a3bf;text-align:center;">Book A Cab</h3>
                      {% csrf_token %}

                        <p style="font-family: sans-serif;font-size:20px;" >Enter Location:</p>
                        <input type="text" id="mapsearch1" name="location" placeholder="Enter location"><br><br>
                        <input type="submit" name="submit" value="Book Now" class="btn btn-info">
                  </div>
                </form>
          </div>

  </div>
</div>
</div>
</div>
</div>

<!-- <a class="btn btn-success" style="background-color: #57cbcc;width:100px;height:30px;" href="{% url 'touristcars:booktourcar' item.auto_increment_id %}" role="button">Link</a> -->


{% endfor %}
</div>

<script>
    // If user clicks anywhere outside of the modal, Modal will close

    var modal = document.getElementById('modal-wrapper');

    window.onclick = function(event) {
      if (event.target == modal) {
          modal.style.display = "none";
      }
    }


</script>


  <script src="http://maps.google.com/maps/api/js?key=AIzaSyCe2otGPKiUf4Qq35MmOfDWHaQm-Cjtopw&libraries=places"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

  <script>



            var searchBox = new google.maps.places.SearchBox(document.getElementById('mapsearch1'));


  </script>




{% endblock body_block %}

airportcars/templates/airportcars/each_histroy.html
{% extends 'index.html' %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% block slidecss %}
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCe2otGPKiUf4Qq35MmOfDWHaQm-Cjtopw"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>
  function calculateRoute(from, to) {
    // Center initialized to Naples, Italy
    var myOptions = {
      zoom: 10,
      center: new google.maps.LatLng(13.5232, 79.9982),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    // Draw the map
    var mapObject = new google.maps.Map(document.getElementById("map"), myOptions);

    var directionsService = new google.maps.DirectionsService();
    var directionsRequest = {
      origin: from ,
      destination: to,
      travelMode: google.maps.DirectionsTravelMode.DRIVING,

    };
    directionsService.route(
      directionsRequest,
      function(response, status)
      {
        if (status == google.maps.DirectionsStatus.OK)
        {
          new google.maps.DirectionsRenderer({
            map: mapObject,
            directions: response
          });
        }
        else
          $("#error").append("Unable to retrieve your route<br />");
      }
    );
  }

  $(document).ready(function() {

    calculateRoute($("#from").val(), $("#to").val());

  });
  document.write()

</script>
<style>

      #map {
        width: 400px;
        height: 400px;
      }
</style>
{% endblock slidecss %}



{% block body_block %}
<br>
<h1 class="card-title" style="text-align:center;font-family:poppins;font-size:50px">Airport Cabs History</h1>

<div class="card" style="position: absolute;top:200px;height:500px;width:1350px;">
  <div class="card-body" >
      <img src="{{ trip.airport_car.car_photo.url }}" alt="Card image" style="width:300px;height:300px;">
      <div class="text" style="position:absolute;left:400px;top:80px;width:400px;font-size: 20px;">
          <b>From Location:</b> {{trip.from_location}}<br>
          <b>To Location:</b> {{trip.to_location}}<br>
          <b>Date:</b> {{trip.date}}<br>
          <b>Car Name:</b> {{trip.airport_car.car_name}}<br>
          <b>Price:</b> Rs.{{trip.airport_car.price}}<br>
         </div>
  </div>


  <div class="map" style="position: absolute;right:50px">
      <form id="calculate-route" name="calculate-route"  method="get">
          <input type="hidden" id="from" name="from"  value="{{trip.from_location}}" placeholder="Type an address"   />
        <br>

        <input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{trip.to_location}}"  />
      </form>
      <div id="map"></div>

      <p id="error"></p>

  </div>
{% endblock body_block %}