airportcars/urls.py
from django.urls import path
from airportcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='airportcars'

urlpatterns = [
    path('bookairportcar/',views.bookairportcar,name='bookairportcar'),
    path('book_a_car/(<int:air_id>)',views.book_a_car,name='book_a_car'),
    path('airportcars_history/',views.tourists_view_history,name='airportcars_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')

]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmsproject/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('accounts.urls')),
    path('rentedcars/',include('rentedcars.urls')),
    path('taxis/',include('taxis.urls')),
    path('contacts/',include('emergencycontacts.urls')),
    path('tourist/',include('touristcars.urls')),
    path('weddingcar/',include('weddingcars.urls')),
    path('airportcars/',include('airportcars.urls')),
    path('notifications/',include('notifications.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taxis/urls.py
from django.urls import path
from taxis import views

app_name='taxis'

urlpatterns = [
    path('booktaxi/',views.booktaxi,name='booktaxi'),
    path('avail_taxi/',views.avail_taxi,name='avail_taxi'),
    path('accept_taxi/(<int:accept_id>)',views.accept_taxi,name='accept_taxi'),
    path('your_trip/',views.your_trip,name='your_trip'),
    path('endtrip/(<int:end_id>)',views.endtrip,name='endtrip'),
    # path('all_trips/',views.all_trips,name='all_trips'),
    path('book_driver/',views.book_driver,name='book_driver'),
    path('book_d/(<int:driver_id>)',views.book_d,name='book_d'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map'),
    path('taxi_view_history/',views.taxi_view_history,name='taxi_view_history'),

]

taxis/models.py
from django.db import models
from accounts.models import *
import datetime

# Create your models here.
class TaxiBooking(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    user_booking = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)
    date = models.DateField()

    class Meta:
        indexes = [
            models.Index(fields = ['user_booking',]),
        ]


class BookedTaxi(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    taxi_booking_details = models.ForeignKey(TaxiBooking,on_delete=models.CASCADE)
    taxi_booked = models.ForeignKey(TaxiProfile,on_delete=models.CASCADE)
    time = models.TimeField()
    active = models.BooleanField()

    class Meta:
        indexes = [
            models.Index(fields = ['active',]),
            models.Index(fields = ['taxi_booking_details',]),
            models.Index(fields = ['taxi_booked',]),
        ]


class BookedDriver(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    user_booked = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    driver = models.ForeignKey(DriverProfile,on_delete=models.CASCADE)
    date = models.DateField()

taxis/forms.py
from django import forms
from taxis.models import *

class TaxiBookingForm(forms.ModelForm):

    class Meta():
        model = TaxiBooking
        fields = ('from_location','to_location')

taxis/views.py
from django.shortcuts import render,redirect
from taxis.forms import *
from taxis.models import *
from notifications.models import *
from accounts.models import *
from rentedcars.models import *
from django.utils import timezone
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from geopy.geocoders import Nominatim

import datetime

# Create your views here.

@login_required
def booktaxi(request):
    geolocator = Nominatim()
    if request.method == 'POST':
        from_location = request.POST.get('from_location_taxi')
        to_location = request.POST.get('to_location_taxi')
        u=UserProfile.objects.get(user=request.user)
        if u.user_type=='U':
            TaxiBooking.objects.create(user_booking=u,date=timezone.now().date(),from_location=from_location,to_location=to_location)
            return redirect('taxis:avail_taxi')
    return redirect('accounts:home')


@login_required
def avail_taxi(request):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        details=TaxiBooking.objects.filter(user_booking=u).last()
        taxi = TaxiProfile.objects.filter(location=details.from_location,active=True)
    return render(request,'taxis/avail_taxi.html',{'taxi':taxi})

@login_required
def accept_taxi(request,accept_id):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        item = TaxiProfile.objects.get(pk = accept_id)
        details=TaxiBooking.objects.filter(user_booking=u).last()
        BookedTaxi.objects.create(taxi_booking_details=details,taxi_booked=item,time=timezone.now().time(),active=True)
        NotificationList.objects.create(message='Taxi is booked',read=False,user=u)
    return redirect('accounts:home')

#
# @login_required
# def all_trips(request):
#     u= UserProfile.objects.get(user=request.user)
#     if u.user_type=='U':
#         return render(request,'taxis/mytrip.html')

@login_required
def your_trip(request):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        # mytrip=BookedTaxi.objects.raw("CALL Getbookedtaxitrips()")
        mytrip=BookedTaxi.objects.filter(active=True)
    return render(request,'taxis/trip.html',{'mytrip':mytrip,'u':u,})


@login_required
def endtrip(request,end_id):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        item = BookedTaxi.objects.get(pk = end_id)
        item.active=False
        item.save()
        t = TaxiProfile.objects.get(pk=item.taxi_booked.pk)
        t.location=item.taxi_booking_details.to_location
        t.save()

        rating=request.POST.get('rating')
        taxi_driver = UserProfile.objects.get(user=item.taxi_booked.user.user)
        print(taxi_driver)
        taxi_driver.rating=rating
        print(rating)
        print(taxi_driver.rating)
        taxi_driver.save()
        NotificationList.objects.create(message='you have ended your trip',read=False,user=u)
    return redirect('accounts:home')




@login_required
def book_driver(request):
    u =UserProfile.objects.get(user=request.user)
    if u.user_type == 'U':
        geolocator = Nominatim()
        if request.method == 'POST':
            location = request.POST.get('location_driver')
            drivers = DriverProfile.objects.filter(location=location,is_booked=False,active=True)
            return render(request,'taxis/drivers.html',{'drivers':drivers})


@login_required
def book_d(request,driver_id):
    u =UserProfile.objects.get(user=request.user)
    item = DriverProfile.objects.get(pk = driver_id)
    item.is_booked = True
    item.save()

    BookedDriver.objects.create(user_booked = u,driver = item,date =timezone.now().date())
    NotificationList.objects.create(message='booked a driver',read=False,user=u)
    return redirect('accounts:home')

@login_required
def display_map(request,map_id):
    u=UserProfile.objects.get(user=request.user)
    trip = BookedTaxi.objects.get(pk = map_id)
    return render(request,'taxis/each_history.html',{'trip':trip})


@login_required
def taxi_view_history(request):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type == 'T':
        t=TaxiProfile.objects.get(user=u)
        all_trips = BookedTaxi.objects.filter(taxi_booked=t)
        return render(request,'taxis/taxi_history.html',{'all_trips':all_trips,})
    elif u.user_type == 'U':
        t=TaxiBooking.objects.filter(user_booking=u).last()
        all_trips=BookedTaxi.objects.filter(taxi_booking_details=t)
        return render(request,'taxis/user_history.html',{'all_trips':all_trips,})

taxis/templates/taxis/avail_taxi.html
	{% extends 'index.html' %}
	{% load static %}


	{% block slidecss %}
	<style>
	.bg
	{
		background: url("/static/images/t1.jpeg") 100% 0 no-repeat fixed;
	     color: white;
	     height: 650px;
	     padding: 100px 0 0 0;

	}
	.card {
	  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
	  transition: 0.3s;
	  width: 60%;
	  height: 300px;
	  border-radius: 5px;
	}

	.card:hover {
	  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
	}



	.container {
	  padding: 3px 10px;
	}

	</style>
	{% endblock slidecss %}


	{% block body_block %}


	<center>
	<br>
	{% for item in taxi %}

	<div >
	<div class="card" style="text-align: center;" >

	  <div class="container">
	    <div style ="text-align: center;padding:35px;">



	  	<img src="{{item.user.profile_pic.url}}" style="float:left;padding:20px;height:200px;width:35%">
	    <b>Taxi Name:</b> {{ item.taxi_name }}<br>
	   	<b>Taxi Num:</b> {{ item.taxi_num }}<br>
	    <b>User:</b> {{ item.user.user }}<br>
	    <b>Location:</b> {{ item.location }}<br>
	    <b>Rating:</b> {{ item.user.rating }}<br>
	    <b>Price:</b> Rs.{{ item.price }}<br>
	    <a href="{% url 'taxis:accept_taxi' item.auto_increment_id %}" class="btn btn-info" role="button">BookNow</a>



	</div>
	  </div>
	</div><br></div>
	{% endfor %}</center>

	{% endblock body_block %}

taxis/templates/taxis/booktaxi.html
{% load crispy_forms_tags %}




  <h3 style="color:red">Book a taxi</h3>
<form method="post">
  {% csrf_token %}
  <br>
  from location
  <input type="text" id="mapsearch1" name="from_location"><br>
  <input type="text" id="mapsearch2" name="to_location"><br>
  <button type="submit" class="btn btn-success">with location</button>
</form>


  <script src="http://maps.google.com/maps/api/js?key=AIzaSyCe2otGPKiUf4Qq35MmOfDWHaQm-Cjtopw&libraries=places"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

  <script>



    var searchBox = new google.maps.places.SearchBox(document.getElementById('mapsearch1'));
    var searchBox = new google.maps.places.SearchBox(document.getElementById('mapsearch2'));


  </script>

taxis/templates/taxis/drivers.html
{%extends 'index.html'%}
{% block slidecss %}
{% load static %}


<style>
.bg
{
	background: url("/static/images/t1.jpeg") 100% 0 no-repeat fixed;
     color: white;
     height: 650px;
     padding: 100px 0 0 0;

}
.card {
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  width: 60%;
  height: 300px;
  border-radius: 5px;
  padding-top:30px;
}

.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}



.container {

  padding-top:3px;
  height:400px;
  width:800px;
}

</style>
{% endblock slidecss %}

{% block body_block %}


{%if drivers%}
<center><br>
{% for item in drivers %}


  <div class="card" style="text-align: center;" >

    <div class="container">
      <div style ="padding:35px;">



    	<img src="{{item.user.profile_pic.url}}" style="float:left;padding:20px;height:200px;width:35%">
      <b>Location:</b> {{ item.location }}
     	<b>Price:</b> {{ item.price }}
      <b>User:</b> {{ item.license_no }}
      <b>Price:</b> Rs.{{ item.price }}
      <a href="{% url 'taxis:book_d' item.auto_increment_id %}" class="btn btn-info" role="button">Book Driver</a>


  </div>
    </div>
  </div><br>

{% endfor %}</center>


{% else %}
<h3>no drivers</h3>\

{% endif %}
{% endblock body_block %}

taxis/templates/taxis/mytrip.html
{% extends 'index.html' %}
{% load static %}

<!--
<html>
  <head>
    <meta charset="UTF-8" />
    <title></title>
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyCe2otGPKiUf4Qq35MmOfDWHaQm-Cjtopw"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script>
      function calculateRoute(from, to) {
        // Center initialized to Naples, Italy
        var myOptions = {
          zoom: 10,
          center: new google.maps.LatLng(13.5232, 79.9982),
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        // Draw the map
        var mapObject = new google.maps.Map(document.getElementById("map"), myOptions);

        var directionsService = new google.maps.DirectionsService();
        var directionsRequest = {
          origin: from ,
          destination: to,
          travelMode: google.maps.DirectionsTravelMode.DRIVING,

        };
        directionsService.route(
          directionsRequest,
          function(response, status)
          {
            if (status == google.maps.DirectionsStatus.OK)
            {
              new google.maps.DirectionsRenderer({
                map: mapObject,
                directions: response
              });
            }
            else
              $("#error").append("Unable to retrieve your route<br />");
          }
        );
      }

      $(document).ready(function() {
        calculateRoute($("#from").val(), $("#to").val());
      });
      document.write()
    </script>
    <style type="text/css">
      #map {
        width: 400px;
        height: 400px;
        margin-top: 10px;
      }
    </style>
  </head>
  <body>
    {% for item in mytrip %}

      {% if item.taxi_booking_details.user_booking == u %}

      {{ item.taxi_booking_details.from_location }}
      {{ item.taxi_booking_details.to_location }}
      {{ item.taxi_booking_details.date }}
      {{ item.taxi_booked.taxi_name }}
      {{ item.taxi_booked.taxi_num }}
      {{ item.taxi_booked.price }}
      {{ item.taxi_booked.active }}
      <a  href="{% url 'taxis:endtrip' item.auto_increment_id %}" role="button">endtrip</a>

      <form id="calculate-route" name="calculate-route" action="#" method="get">
          <input type="hidden" id="from" name="from"  value="{{ item.taxi_booking_details.from_location }}" placeholder="Type an address"   />
        <br>

        <input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{ item.taxi_booking_details.to_location }}"  />

      </form>
      <div id="map"></div>

      <p id="error"></p>

      {% endif %}

    {% endfor %}

<br>
<h3>cartrip</h3>
<div>
  {% for value in cartrip %}

    {% if value.booking_Details.user_booked == u %}

    {{ value.booking_Details.car_location }}
    {{ value.booking_Details.to_location }}
    {{ value.booking_Details.from_date }}
    {{ value.booking_Details.to_date }}
    {{ value.car_rented.user_rented }}
    <form id="calculate-route" name="calculate-route" action="#" method="get">
        <input type="hidden" id="from" name="from"  value="{{ value.booking_Details.car_location }}" placeholder="Type an address"   />
      <br>

      <input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{ value.booking_Details.to_location }}"  />

    </form>
    <div id="map"></div>

    <p id="error"></p>

    {% endif %}

  {% endfor %}
</div>

  </body>
</html> -->

{% block body_block %}


<div style="background-image: url('{% static 'images/2.jpeg' %}');background-size:cover;background-repeat:no-repeat;height: 420px;">
  <a href="{% url 'taxis:your_trip' %}" style="position:absolute;top:470px;left:300px;font-size:50px;"class="btn btn-info">My trips</a>
  <a href="#" style="position:absolute;top:470px;left:670px;font-size:50px;"class="btn btn-info">My trips</a>
  <a href="#" style="position:absolute;top:470px;right:300px;font-size:50px;"class="btn btn-info">My trips</a>
</div>
<br>


{% endblock body_block %}

taxis/templates/taxis/rating_pay.html
<form method="post">
  {% csrf_token %}
  <input type="number" name="rating" value="">
  <input type="submit" name="submit" value="submit">
</form>

taxis/templates/taxis/taxi_history.html
{% extends 'taxi_index.html' %}
{% load static %}

{% block body_block %}

<style>
    .card{
        margin: 1rem;
        padding: 10px;
        width: 200px;
        display: inline-block;
    }
    .image{
        background-image: url("{% static 'images/banner2.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }
    a{
        font-family: poppins;
        font-size: 18px;
    }
</style>
    <div class="image" style="width:1530px;height:300px;"><div style="color: white;font-size: 50px;font-family: poppins;position: absolute;left:40%;top:30%">Taxi History</div></div>

    {% for item in all_trips %}

        <div class="card" style="width: 22rem;">
            <div class="card-body">
                <a>Active status:</a>{{ item.active }}<br>
                <a>Taxi Profile:</a>{{ item.taxi_booking_details.user_booking.user }}<br>
                <a>Booked By:</a>{{item.taxi_booking_details}}<br>
                <a>From Location:</a>{{ item.taxi_booking_details.from_location }}<br>
                <a>To Location:</a>{{ item.taxi_booking_details.to_location }}<br>
                <a>Rating:</a>{{ item.taxi_booked.user.rating }}<br>
                <a>Time:{{item.time}}</a><br>
                <a class="btn btn-primary" href="{% url 'taxis:display_map' item.auto_increment_id %}" role="button">History</a>
            </div>
        </div>

        <!-- <form id="calculate-route" name="calculate-route" action="{% url 'taxis:display_map' item.auto_increment_id %}" method="POST">
  {%csrf_token%}
    <input type="hidden" id="from" name="from"  value="{{ item.booking_Details.car_location }}" placeholder="Type an address"   />
  <br>

  <input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{ item.booking_Details.to_location }}"  />
<input type="submit" /> -->
    {% endfor %}


{% endblock body_block %}

taxis/templates/taxis/trip.html
{% extends 'index.html' %}
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% block slidecss %}
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCe2otGPKiUf4Qq35MmOfDWHaQm-Cjtopw"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>
  function calculateRoute(from, to) {
    // Center initialized to Naples, Italy
    var myOptions = {
      zoom: 10,
      center: new google.maps.LatLng(13.5232, 79.9982),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    // Draw the map
    var mapObject = new google.maps.Map(document.getElementById("map"), myOptions);

    var directionsService = new google.maps.DirectionsService();
    var directionsRequest = {
      origin: from ,
      destination: to,
      travelMode: google.maps.DirectionsTravelMode.DRIVING,

    };
    directionsService.route(
      directionsRequest,
      function(response, status)
      {
        if (status == google.maps.DirectionsStatus.OK)
        {
          new google.maps.DirectionsRenderer({
            map: mapObject,
            directions: response
          });
        }
        else
          $("#error").append("Unable to retrieve your route<br />");
      }
    );
  }

  $(document).ready(function() {
    calculateRoute($("#from").val(), $("#to").val());
  });
  document.write()
</script>

<style>
      .card{
        border: none;
        right:300px;
        height:430px;
        width:1000px;
        position:absolute;
      }
      .card-body{
        left:60px;
        position:absolute;
      }
      .card-body a{
        font-family:sans serif;
        font-size:20px;
      }
      #map {
        width: 400px;
        height: 400px;
        left:500px;
        top:0px;
        position:absolute;
        margin-top: 10px;
      }
      form{
        padding:10px;
        margin: 0.1rem;
      }
      form a{
        font-family:sans serif;
        color:#18a3bf;
      }
      .form{
          background-color: #fefefe;
          margin: 4% auto 15% auto;
          border: 1px solid #888;
          width: 500px;
          padding-bottom: 30px;
      }
      .modal {
          display:none;
          z-index: 1;
          left: 0;
          top: 0;
          width: 100%;
          height: 100%;
          overflow: auto;
          background-color: rgba(0,0,0,0.4);
      }
      .close {
          position: absolute;
          right: 25px;
          top: 0;
          color: #000;
          font-size: 35px;
          font-weight: bold;
      }
      .close:hover,.close:focus {
          color: #57cbcc;
          cursor: pointer;
      }

      input[type=number]{
          position: center;
          padding: 12px 20px;
          margin: 8px 26px;
          display: inline-block;
          border-radius: 10%;
          border: 1px solid #ccc;
          box-sizing: border-box;
          font-size:16px;
      }
      .image{
          background-image: url("{% static 'images/banner2.jpg' %}");
          background-size: cover;
          background-repeat: no-repeat;
      }
</style>
{% endblock slidecss %}

{% block body_block %}
<div class="image" style="width:1530px;height:300px;"><div style="color: white;font-size: 50px;font-family: poppins;position: absolute;left:35%;top:30%">Taxi Trip Details</div></div>

<div class="card">
  <div class="card-body">
    {% for item in mytrip %}
      {% if item.taxi_booking_details.user_booking == u %}
      <a>From location:</a>{{ item.taxi_booking_details.from_location }}<br>
      <a>To location:</a>{{ item.taxi_booking_details.to_location }}<br>
      <a>Taxi details:</a>{{ item.taxi_booking_details.date }}<br>
      <a>Taxi Name:</a>{{ item.taxi_booked.taxi_name }}<br>
      <a>Taxi Number:</a>{{ item.taxi_booked.taxi_num }}<br>
      <a>Price:</a>{{ item.taxi_booked.price }}<br>
      <a>Active state:</a>{{ item.taxi_booked.active }}<br>
      <br>
      <button onclick="document.getElementById('modal-wrapper').style.display='block'" class="btn btn-main" style="background-color:#57cbcc">Give Rating</button>
      <div id="modal-wrapper" class="modal">
           <form class="form" method="post" action="{% url 'taxis:endtrip' item.auto_increment_id %}">
              <div>
                  <span onclick="document.getElementById('modal-wrapper').style.display='none'" class="close" title="Close PopUp">&times;</span>
              </div>
              <div class="container">
                <h3 style="color:#18a3bf">Give Rating</h3>
                  {% csrf_token %}

                  <p style="font-family: sans-serif;" >Rating</p>
                  <input type="number" name="rating" placeholder="Rating"><br>


                  <button style="background-color: #57cbcc;width:100px;height:30px;" type="submit" class="btn btn-success">End Trip</button>
                  </div>
          </form>
          </div>
      <form id="calculate-route" name="calculate-route" action="#" method="get">
          <input type="hidden" id="from" name="from"  value="{{ item.taxi_booking_details.from_location }}" placeholder="Type an address"   />
        <br>

        <input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{ item.taxi_booking_details.to_location }}"  />

      </form>
      <div id="map"></div>

      <p id="error"></p>

      {% endif %}

    {% endfor %}
  </div>
</div>



<script>
    // If user clicks anywhere outside of the modal, Modal will close

    var modal = document.getElementById('modal-wrapper');

    window.onclick = function(event) {

      if (event.target == modal) {
          modal.style.display = "none";
      }
    }


</script>
{% endblock body_block %}

taxis/templates/taxis/user_history.html
{% extends 'index.html' %}
{% load static %}

{% block body_block %}
<style>
    .card{
        margin: 1rem;
        padding: 10px;
        width: 200px;
        display: inline-block;
    }
    .image{
        background-image: url("{% static 'images/banner2.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }
    a{
        font-family: poppins;
        font-size: 18px;
    }
</style>
<div class="image" style="width:1530px;height:300px;"><div style="color: white;font-size: 50px;font-family: poppins;position: absolute;left:40%;top:30%">Taxi History</div></div>


{% for item in all_trips %}
<div class="card" style="width: 22rem;">
    <div class="card-body">
      <a>Taxi Profile:</a>{{ item.taxi_booking_details.user_booking.user }}<br>
      <a>Booked By:</a>{{item.taxi_booking_details}}<br>
      <a>From Location:</a>{{ item.taxi_booking_details.from_location }}<br>
      <a>To Location:</a>{{ item.taxi_booking_details.to_location }}<br>
      <a>Rating:</a>{{ item.taxi_booked.user.rating }}<br>
      <a>Time:{{item.time}}</a><br>
      <a class="btn btn-primary" href="{% url 'taxis:display_map' item.auto_increment_id %}" role="button">History</a>
                <!-- <a class="btn btn-primary" href="{% url 'airportcars:display_map' item.auto_increment_id %}" role="button">History</a> -->
<br>
            </div>
        </div>

        <!-- <form id="calculate-route" name="calculate-route" action="{% url 'taxis:display_map' item.auto_increment_id %}" method="POST">
          {%csrf_token%}
            <input type="hidden" id="from" name="from"  value="{{ item.booking_Details.car_location }}" placeholder="Type an address"   />
          <br>

          <input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{ item.booking_Details.to_location }}"  />
        <input type="submit" /> -->
        {% endfor %}


        {% endblock body_block %}