airportcars/urls.py
from django.urls import path
from airportcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='airportcars'

urlpatterns = [
    path('bookairportcar/',views.bookairportcar,name='bookairportcar'),
    path('book_a_car/(<int:air_id>)',views.book_a_car,name='book_a_car'),
    path('airportcars_history/',views.tourists_view_history,name='airportcars_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')

]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmsproject/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('accounts.urls')),
    path('rentedcars/',include('rentedcars.urls')),
    path('taxis/',include('taxis.urls')),
    path('contacts/',include('emergencycontacts.urls')),
    path('tourist/',include('touristcars.urls')),
    path('weddingcar/',include('weddingcars.urls')),
    path('airportcars/',include('airportcars.urls')),
    path('notifications/',include('notifications.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentedcars/urls.py
from django.urls import path
from rentedcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='rentedcars'


urlpatterns = [
    path('rentcardisplay/',views.rentcardisplay,name='rentcardisplay'),
    path('display_avail_cars/',views.display_avail_cars,name='display_avail_cars'),
    path('rentcarform/',views.rentcarform,name='rentcarform'),
    # path('bookcabform/',views.bookcabform,name='bookcabform'),
    path('book/(<int:book_id>)',views.book_my_car,name='book_my_car'),
    path('display_req/',views.display_req,name='display_req'),
    path('display_req/(<int:req_id>)',views.accept,name='display_req_accept'),
    path('history/',views.rentalhistory,name='rentalhistory'),
    path('cab_trip/',views.cab_trip,name='cab_trip'),
    path('endcabtrip/(<int:endcab_id>)',views.endcabtrip,name='endcabtrip'),
    path('trial/<int:trial_id>)',views.trial,name='trial'),
    path('car_history/',views.car_view_history,name='car_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taxis/urls.py
from django.urls import path
from taxis import views

app_name='taxis'

urlpatterns = [
    path('booktaxi/',views.booktaxi,name='booktaxi'),
    path('avail_taxi/',views.avail_taxi,name='avail_taxi'),
    path('accept_taxi/(<int:accept_id>)',views.accept_taxi,name='accept_taxi'),
    path('your_trip/',views.your_trip,name='your_trip'),
    path('endtrip/(<int:end_id>)',views.endtrip,name='endtrip'),
    # path('all_trips/',views.all_trips,name='all_trips'),
    path('book_driver/',views.book_driver,name='book_driver'),
    path('book_d/(<int:driver_id>)',views.book_d,name='book_d'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map'),
    path('taxi_view_history/',views.taxi_view_history,name='taxi_view_history'),

]

touristcars/urls.py
from django.urls import path
from touristcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='touristcars'

urlpatterns = [
    path('booktour/',views.booktour,name='booktour'),
    path('booktourcar/(<int:tour_id>)',views.booktourcar,name='booktourcar'),
    path('touristcars_history/',views.tourists_view_history,name='touristcars_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weddingcars/urls.py
from django.urls import path
from weddingcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='weddingcars'

urlpatterns = [
    path('weddingcardisplay/',views.weddingcardisplay,name='weddingcardisplay'),
    path('weddingcar_book/(<int:wed_id>)',views.weddingcar_book,name='weddingcar_book'),
    path('weddingcars_history/',views.tourists_view_history,name='weddingcars_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentedcars/models.py
from django.db import models
from accounts.models import UserProfile

# Create your models here.
class CarDetail(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    car_name = models.CharField(max_length=30)
    car_num = models.CharField(max_length=30)
    regno_expdt = models.DateField()
    mileage = models.IntegerField()
    user_choices = (
        ('N', 'nonac'),
        ('A', 'ac'),
    )
    car_type=models.CharField(choices=user_choices,max_length=2)
    car_pic = models.ImageField(upload_to='images/rentedcars/')

class RentedCar(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    user_rented = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    car_details = models.ForeignKey(CarDetail,on_delete=models.CASCADE)
    car_location = models.CharField(max_length=100)
    from_date = models.DateField()
    to_date = models.DateField()
    price = models.IntegerField()
    is_booked = models.BooleanField()

    class Meta:
        indexes = [
            models.Index(fields = ['car_location','from_date','to_date','is_booked',]),
        ]


class BookingDetail(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    user_booked = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    from_date = models.DateField()
    to_date = models.DateField()
    car_location = models.CharField(max_length=100,default='')
    to_location = models.CharField(max_length=100,default='')

    class Meta:
        indexes = [
            models.Index(fields = ['user_booked',]),
        ]


class BookedCar(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    car_rented = models.ForeignKey(RentedCar,on_delete=models.CASCADE)
    booking_Details = models.ForeignKey(BookingDetail,on_delete=models.CASCADE)
    accept = models.BooleanField()
    active = models.BooleanField()
    date = models.DateField()

    class Meta:
        indexes = [
            models.Index(fields = ['accept','active',]),
        ]

rentedcars/forms.py
from django import forms
from rentedcars.models import *

from crispy_forms.helper import FormHelper



class CarDetailForm(forms.ModelForm):

    class Meta():
        model = CarDetail
        fields = ('car_name','car_num','regno_expdt','mileage','car_type','car_pic',)
        widgets={
            'car_name':forms.TextInput(attrs={'id':'car_name','placeholder':'carname'}),
            'car_num':forms.TextInput(attrs={'id':'car_num','placeholder':'car num'}),
            'regno_expdt':forms.DateInput(attrs={'id':'regno_expdt','placeholder':'regno_expdt'}),
            'mileage':forms.NumberInput(attrs={'id':'mileage','placeholder':'mileage'}),
            'car_pic':forms.FileInput(attrs={'id':'pic'})
        }
        labels={
            'car_name':'',
            'car_num':'',
            'regno_expdt':'',
            'mileage':'',
            'car_type':'',
            'car_pic':'',

        }


class RentedCarForm(forms.ModelForm):

    class Meta():
        model = RentedCar
        fields = ('from_date','to_date','price')
        widgets={
            'from_date':forms.TextInput(attrs={'id':'from_date','placeholder':'from_date'}),
            'to_date':forms.TextInput(attrs={'id':'to_date','placeholder':'to_date'}),
            'price':forms.TextInput(attrs={'id':'price','placeholder':'Price'}),
        }
        labels={
            'from_date':'',
            'to_date':'',
            'price':'',
        }


# class CarDetailForm(forms.ModelForm):
#
#     class Meta():
#         model = CarDetail
#         fields = ('car_name','car_num','regno_expdt','mileage','car_type','car_pic',)
#
# class RentedCarForm(forms.ModelForm):
#
#     class Meta():
#         model = RentedCar
#         fields = ('from_date','to_date','price')


class BookingDetailForm(forms.ModelForm):

    class Meta():
        model = BookingDetail
        fields = ('from_date','to_date')
        widgets={
            'from_date':forms.TextInput(attrs={'id':'from_date','placeholder':'from_date'}),
            'to_date':forms.TextInput(attrs={'id':'to_date','placeholder':'to_date'}),
        }
        labels={
            'from_date':'',
            'to_date':'',
        }

rentedcars/views.py
from django.shortcuts import render,redirect
from rentedcars.forms import *
from rentedcars.models import *
from notifications.models import *
from accounts.models import *
from django.contrib.auth import authenticate,login,logout
from geopy.geocoders import Nominatim

from django.utils import timezone
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def rentcardisplay(request):
    u=UserProfile.objects.get(user=request.user)

    if u.user_type=='U':
        rented_cars = RentedCar.objects.filter(user_rented=u)
        return render(request, 'rentedcars/rentcardisplay.html',{'rented_cars':rented_cars})
    else:
        return HttpResponse("not a valid user")

@login_required
def rentcarform(request):
    geolocator = Nominatim()
    car_location = request.POST.get('car_location')
    detailsform = CarDetailForm(request.POST or None, request.FILES or None)
    form = RentedCarForm(request.POST or None)
    if form.is_valid() and detailsform.is_valid():
        u=UserProfile.objects.get(user=request.user)
        if u.user_type=='U':

            detailsforminstance=detailsform.save(commit=False)
            detailsforminstance.save()

            forminstance=form.save(commit=False)
            forminstance.user_rented=u
            forminstance.car_location=car_location
            forminstance.car_details=detailsforminstance
            forminstance.is_booked=False
            forminstance.save()
            NotificationList.objects.create(message='you have succesfully rented your car with num '+str(forminstance.car_details.car_num),read=False,user=u)
        return redirect('rentedcars:rentcardisplay')
    return render(request,'rentedcars/rentcarform.html' ,{'detailsform':detailsform,'form':form,})


# @login_required
# def bookcabform(request):
#     geolocator = Nominatim()
#     car_location = request.POST.get('car_location')
#     to_location = request.POST.get('to_location')
#     form = BookingDetailForm(request.POST or None)
#     if form.is_valid():
#         u=UserProfile.objects.get(user=request.user)
#         if u.user_type=='U':
#
#             forminstance=form.save(commit=False)
#             forminstance.user_booked=u
#             forminstance.to_location=request.POST.get('to_location')
#             forminstance.car_location=request.POST.get('car_location')
#             forminstance.save()
#             return redirect('rentedcars:display_avail_cars')
#     return render(request,'rentedcars/form_book.html' ,{'form':form})


@login_required
def display_avail_cars(request):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        details=BookingDetail.objects.filter(user_booked=u).last()
        cars_avail = RentedCar.objects.filter(car_location=details.car_location,from_date=details.from_date,to_date=details.to_date,is_booked=False)
        return render(request,'rentedcars/display_avail_cars.html' ,{'cars_avail':cars_avail,'u':u,})

@login_required
def book_my_car(request,book_id):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        details=BookingDetail.objects.filter(user_booked=u).last()
        item = RentedCar.objects.get(pk = book_id)
        if details.user_booked != item.user_rented:
            BookedCar.objects.create(car_rented=item,booking_Details=details,accept=False,active=False,date=timezone.now().date())
            NotificationList.objects.create(message='you have succesfully requested user '+str(item.user_rented.user),read=False,user=u)
            NotificationList.objects.create(message='you have succesfully requested user '+str(u.user),read=False,user=item.user_rented)
        else:
            return HttpResponse("same user cant book his car")
        return redirect('accounts:home')

@login_required
def display_req(request):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        cars_req=BookedCar.objects.raw("CALL Getallrequests()")
        print('used procedure')
        return render(request,'rentedcars/display_cars_req.html' ,{'cars_req':cars_req,'u':u,})


@login_required
def accept(request,req_id):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        item = BookedCar.objects.get(pk = req_id)
        if request.method == 'POST':
            for key in request.POST.items():
                if key[0] == 'decline':
                    item.delete()
        else:
            item.accept = True
            item.active = True
            item.car_rented.is_booked = True
            item.save()
            k = RentedCar.objects.get(pk=item.car_rented.pk)
            k.is_booked=True
            k.save()

            NotificationList.objects.create(message='you have succesfully accepted user '+str(item.booking_Details.user_booked.user),read=False,user=u)
            NotificationList.objects.create(message=str(u.user)+' has accepted your request',read=False,user=item.booking_Details.user_booked)
        return redirect('rentedcars:display_req')

#
# @login_required
# def decline(request,req2_id):
#     y=UserProfile.objects.get(user=request.user)
#     if y.user_type=='U':
#         item = BookedCar.objects.get(pk = req2_id)
#         item.delete()
#         return redirect('rentedcars:display_req')



@login_required
def rentalhistory(request):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        # SELECT * FROM rentedcars_bookedcar WHERE accept='1';
        history = BookedCar.objects.filter(accept=True)
        return render(request,'rentedcars/rentalhistory.html',{'history':history,'u':u,})








@login_required
def cab_trip(request):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        cartrip=BookedCar.objects.raw("CALL Getbookedcar()")
        # cartrip=BookedCar.objects.filter(active=True)
    return render(request,'rentedcars/cabtrip.html',{'u':u,'cartrip':cartrip,})


@login_required
def endcabtrip(request,endcab_id):
    u=UserProfile.objects.get(user=request.user)
    if u.user_type=='U':
        item = BookedCar.objects.get(pk = endcab_id)
        item.active=False
        item.save()


        rating=request.POST.get('rating')
        rented_user = UserProfile.objects.get(user=item.car_rented.user_rented.user)
        rented_user.rating=rating
        rented_user.save()
    return redirect('accounts:home')


def trial(request,trial_id):
    item = BookedCar.objects.get(pk = trial_id)
    return render(request,'rentedcars/map.html',{'item':item})

@login_required
def display_map(request,map_id):
    u=UserProfile.objects.get(user=request.user)
    trip = BookedCar.objects.get(pk = map_id)
    return render(request,'rentedcars/each_history.html',{'trip':trip})


@login_required
def car_view_history(request):
    u=UserProfile.objects.get(user=request.user)
    all_trips = BookedCar.objects.filter(active=True)
    return render(request,'rentedcars/car_history.html',{'all_trips':all_trips,'u':u})

rentedcars/templates/rentedcars/cabtrip.html
  {% extends 'index.html' %}
{% load static %}

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  {% block slidecss %}

  <style>
        .card{
          margin: 5rem;
          display: inline-block;
          height:250px;
          width: 500px;
          position:relative;
          border:none;
        }
        a{
          /* font-family: poppins; */
          font-size: 20px;
          color: #18a3bf;
        }
        form{
          padding:10px;
          margin: 0.1rem;
        }
        form a{
          font-family:sans serif;
          color:#18a3bf;
        }
        .form{
            background-color: #fefefe;
            margin: 4% auto 15% auto;
            border: 1px solid #888;
            width: 500px;
            padding-bottom: 30px;
        }
        .modal {
            display:none;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0,0,0,0.4);
        }
        .close {
            position: absolute;
            right: 25px;
            top: 0;
            color: #000;
            font-size: 35px;
            font-weight: bold;
        }
        .close:hover,.close:focus {
            color: #57cbcc;
            cursor: pointer;
        }

        input[type=number]{
            position: center;
            padding: 12px 20px;
            margin: 8px 26px;
            display: inline-block;
            border-radius: 10%;
            border: 1px solid #ccc;
            box-sizing: border-box;
            font-size:16px;
        }
        .image{
            background-image: url("{% static 'images/banner2.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
        }
  </style>
  {% endblock slidecss %}

  {% block body_block %}
    <div class="image" style="width:1530px;height:300px;"><div style="color: white;font-size: 50px;font-family: poppins;position: absolute;left:35%;top:30%">Cab History</div></div>

  {% for item in cartrip %}
        {% if item.booking_Details.user_booked == u %}
        <div class="card" style="border:1px solid black">
        <div class="card-body">
        <b>From Date:</b>&nbsp{{ item.booking_Details.from_date }}<br>
        <b>To Date:</b>&nbsp{{ item.booking_Details.to_date }}<br>
        <b>Car Location</b>:&nbsp{{ item.booking_Details.car_location }}<br>
        <b>To Location</b>:&nbsp{{ item.booking_Details.to_location }}<br>
        <b>User</b>:&nbsp{{ item.car_rented.user_rented }}
        <br>
        <button onclick="document.getElementById('modal-wrapper').style.display='block'" class="btn btn-main" style="background-color:#57cbcc">Give Rating</button>
        <div id="modal-wrapper" class="modal">
             <form class="form" method="post" action="{% url 'rentedcars:endcabtrip' item.auto_increment_id %}">
                <div>
                    <span onclick="document.getElementById('modal-wrapper').style.display='none'" class="close" title="Close PopUp">&times;</span>
                </div>
                <div class="container">
                  <h3 style="color:#18a3bf">Give Rating</h3>
                    {% csrf_token %}

                    <p style="font-family: sans-serif;" >Rating</p>
                    <input type="number" name="rating" placeholder="Rating"><br>


                    <button style="background-color: #57cbcc;width:100px;height:30px;" type="submit" class="btn btn-success">End Trip</button>
                    </div>
            </form>
            </div>
        <a href="{% url 'rentedcars:trial' item.auto_increment_id %}" class="btn btn-info">View More</a>
      </div>


        {% endif %}

      {% endfor %}
  </div>

      <script>
          // If user clicks anywhere outside of the modal, Modal will close

          var modal = document.getElementById('modal-wrapper');

          window.onclick = function(event) {

            if (event.target == modal) {
                modal.style.display = "none";
            }
          }


      </script>
  {% endblock body_block %}

rentedcars/templates/rentedcars/car_history.html
{% extends 'index.html' %}
{% load static %}


{% block body_block %}
<style>
    .card{
        margin: 1rem;
        padding: 10px;
        width: 200px;
        display: inline-block;
    }
    .image{
        background-image: url("{% static 'images/banner2.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }
    a{
        font-family: poppins;
        font-size: 18px;
    }
</style>


<div class="image" style="width:1530px;height:300px;"><div style="color: white;font-size: 50px;font-family: poppins;position: absolute;left:40%;top:30%">Booked Cars History</div></div>
{% for item in all_trips %}

    <div class="card" style="width: 22rem;">
        <div class="card-body">
            <a>Active status:</a>{{ item.active }}<br>
            <a>rented by:</a>{{ item.car_rented.user_rented.user }}<br>
            <a>Booked By:</a>{{item.booking_Details.user_booked.user}}<br>
            <a>From Location:</a>{{ item.booking_Details.car_location }}<br>
            <a>To Location:</a>{{ item.booking_Details.to_location }}<br>
            <a class="btn btn-primary" href="{% url 'rentedcars:display_map' item.auto_increment_id %}" role="button">History</a>
        </div>
    </div>

    <!-- <form id="calculate-route" name="calculate-route" action="{% url 'taxis:display_map' item.auto_increment_id %}" method="POST">
{%csrf_token%}
<input type="hidden" id="from" name="from"  value="{{ item.booking_Details.car_location }}" placeholder="Type an address"   />
<br>

<input type="hidden" id="to" name="to" required="required" placeholder="Type an addresss" value="{{ item.booking_Details.to_location }}"  />
<input type="submit" /> -->
{% endfor %}




{% endblock body_block %}

rentedcars/templates/rentedcars/display_avail_cars.html
{% extends 'index.html' %}
{% load static %}


{% block slidecss %}

<style>
.container {
  position: relative;
  width: 50%;

}

.flag{
    float:right;
	color:#48cfad;
	font-size:22px;
	font-weight:600;
}

.image {
  display: block;
  width: 100%;
  height: auto;
}

.overlay {
  position: absolute;
  bottom: 100%;
  left: 0;
  right: 0;
  background-color: #0069d985;
  overflow: hidden;
  width: 100%;
  height:0;
  transition: .5s ease;
}

.container:hover .overlay {
  bottom: 0;
  height: 100%;
}

.text {
  color: white;
  font-size: 20px;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
}
</style>
{% endblock slidecss %}


{% block body_block %}

<div style="position:relative;text-align:center;color:black;">
  <img src="https://images.pexels.com/photos/120049/pexels-photo-120049.jpeg?cs=srgb&dl=automobile-cars-headlights-120049.jpg&fm=jpg" style="opacity:0.7;height:400px;width:100%;">
  <div style="position: absolute;bottom: 0;background: transparent;color: white;width: 100%;padding: 20px;">
  <h1 style="color:#155f99">Rented Cars</h1>
  </div>
</div>

<div style="padding:100px;">
{% for item in cars_avail %}
    {% if item.user_rented == u %}
    {% elif item.is_booked == False %}
<div style="display:inline-block;padding-bottom:150px;">
  <div class="container" style="width:400px;height:350px;">

    <div class="card" >
      <img class="card-img-top" src="{{ item.car_details.car_pic.url }}" alt="Card image" style="width:100%;height:350px;">
      <div class="card-body">
        <h4 class="card-title">{{ item.car_details.car_name }}<span class="flag">Rs {{ item.price }}</span></h4>
      <h5 class="date">Service To:{{ item.car_location }}</h5>
     <div class="overlay">
      <div class="text">
          <h5 class="seats">Car No:{{ item.car_details.car_num }}</h5>
        <h5 class="seats">Mileage:{{ item.car_details.mileage }}</h5>
        <h5 class="seats">Owner Name:{{ item.user_rented.user }}</h5><br><br>
           <a href="{% url 'rentedcars:book_my_car' item.auto_increment_id %}" class="btn btn-primary stretched-link">Send request</a>

      </div>
    </div>
</div>



      </div>
    </div>
  </div>
  {% endif %}
{% endfor %}

</div>



{% endblock body_block %}

rentedcars/templates/rentedcars/form_book.html
{% load crispy_forms_tags %}




  <h3 style="color:red">Book a car for rent</h3>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <br>
  enter location
  <input type="text" id="mapsearch1" name="car_location"><br>
  <input type="text" id="mapsearch2" name="to_location"><br>
  <button type="submit" class="btn btn-info">Book now</button>
</form>


  <script src="http://maps.google.com/maps/api/js?key=AIzaSyCe2otGPKiUf4Qq35MmOfDWHaQm-Cjtopw&libraries=places"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

  <script>



        var searchBox = new google.maps.places.SearchBox(document.getElementById('mapsearch1'));
        var searchBox = new google.maps.places.SearchBox(document.getElementById('mapsearch2'));

  </script>

rentedcars/templates/rentedcars/rating_pay.html
<form method="post">
  {% csrf_token %}
  <input type="number" name="rating" value="">
  <input type="submit" name="submit" value="submit">
</form>

rentedcars/templates/rentedcars/rentalhistory.html
{% extends 'index.html'%}



{% load static %}

{% block slidecss %}


<style>
  .history_btn{
    position:absolute;
    top:450px;
    left:250px;
  }
  .container{
      padding-left:40px;
    }

    .card{
      width:150px;
      height:150px;
    }
    .card-flip > div {
        backface-visibility: hidden;
        transition: transform 400ms;
        transition-timing-function: linear;
        width: 100%;
        height: 100%;
        margin: 0;
        display: flex;
    }

    .card-front {
        transform: rotateY(0deg);
        color:rgba(54,193,226,0.85);
        padding:5px;
        text-align:center;
    }

    .card-back {
        transform: rotateY(180deg);
        position: absolute;
        top: 0;
    }

    .card-flip:hover .card-front {
        transform: rotateY(-180deg);
    }

    .card-flip:hover .card-back {
        transform: rotateY(0deg);
        padding:10px;
    }

</style>


{% endblock slidecss %}


{% block body_block %}

<div class="image_block">
  <img src="https://images.pexels.com/photos/2132603/pexels-photo-2132603.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" style="height:500px;width:100%">
  <div class="btn-group history_btn" role="group" aria-label="Basic example">
    <div class="container" style="display:inline-block;">
        <div class="card" style="display:inline-block;">
            <div class="card card-flip h-100">
                <div class="card-front">
                    <div class="card-body">
                        <h5 class="card-title">Rented Cars History</h5>
                    </div>
                </div>
                <div class="card-back bg-white">
                    <div class="card-body" style="color:rgba(54,193,226,0.85);">
                        <a href="{%url 'rentedcars:rentcardisplay'%}" class="btn btn-outline-primary">History</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card" style="display:inline-block;">
            <div class="card card-flip h-100">
                <div class="card-front">
                    <div class="card-body" >
                        <h5 class="card-title">Booked Cars History</h5>
                    </div>
                </div>
                <div class="card-back bg-white">
                    <div class="card-body" style="color:rgba(54,193,226,0.85);">
                        <a href="{%url 'rentedcars:car_history'%}" class="btn btn-outline-primary">History</a>
                    </div>
                </div>
            </div>
        </diV>
        <div class="card" style="display:inline-block;">
            <div class="card card-flip h-100">
                <div class="card-front">
                    <div class="card-body">
                        <h5 class="card-title">Booked Weddingcars</h5>
                    </div>
                </div>
                <div class="card-back bg-white">
                    <div class="card-body" style="color:rgba(54,193,226,0.85);">
                        <a href="{% url 'weddingcars:weddingcars_history' %}" class="btn btn-outline-primary">History</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card" style="display:inline-block;">
            <div class="card card-flip h-100">
                <div class="card-front">
                    <div class="card-body">
                        <h5 class="card-title">Booked Tourist cars</h5>
                    </div>
                </div>
                <div class="card-back bg-white">
                    <div class="card-body" style="color:rgba(54,193,226,0.85);">
                        <a href="{%url 'touristcars:touristcars_history'%}" class="btn btn-outline-primary">History</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card" style="display:inline-block;">
            <div class="card card-flip h-100">
                <div class="card-front">
                    <div class="card-body">
                        <h5 class="card-title">Booked Airportcars</h5>
                    </div>
                </div>
                <div class="card-back bg-white">
                    <div class="card-body" style="color:rgba(54,193,226,0.85);">
                        <a href="{%url 'airportcars:airportcars_history'%}" class="btn btn-outline-primary">History</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card" style="display:inline-block;">
            <div class="card card-flip h-100">
                <div class="card-front">
                    <div class="card-body">
                        <h5 class="card-title">Booked Taxi History</h5>
                    </div>
                </div>
                <div class="card-back bg-white">
                    <div class="card-body" style="color: rgba(54,193,226,0.85)">
                        <!--{%url 'taxis:taxi_view_history'%}-->
                        <a href="{%url 'taxis:taxi_view_history'%}" class="btn btn-outline-primary">History</a>
                    </div>
                </div>
            </div>
        </div>

  </div>

</div>

{% endblock body_block %}