accounts/urls.py
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static


app_name='accounts'


urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.user_login,name='user_login'),
    path('user_signup/', views.user_signup,name='user_signup'),
    path('user_logout/', views.user_logout,name='user_logout'),
    path('taxi_profile/', views.taxi_profile,name='taxi_profile'),
    # path('driver_profile/', views.driver_profile,name='driver_profile'),
    path('view_profile/',views.view_profile,name='view_profile'),
    path('taxi_home/',views.taxi_home,name='taxi_home'),

]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmsproject/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('accounts.urls')),
    path('rentedcars/',include('rentedcars.urls')),
    path('taxis/',include('taxis.urls')),
    path('contacts/',include('emergencycontacts.urls')),
    path('tourist/',include('touristcars.urls')),
    path('weddingcar/',include('weddingcars.urls')),
    path('airportcars/',include('airportcars.urls')),
    path('notifications/',include('notifications.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emergencycontacts/urls.py
from django.urls import path
from emergencycontacts import views

app_name='emergencycontacts'

urlpatterns=[
    path('add/',views.emergencycontact,name='emergencycontacts'),
    path('sendmail',views.sendmail,name='sendmail'),
]

notifications/urls.py
from django.conf.urls import url
from . import views

app_name = 'notifications'

urlpatterns = [
    #notifications
    url('^$', views.index, name='index'),

    url('update/(?P<notify_id>[0-9]+)', views.update, name='update'),

]

rentedcars/urls.py
from django.urls import path
from rentedcars import views
from django.conf import settings
from django.conf.urls.static import static


app_name='rentedcars'


urlpatterns = [
    path('rentcardisplay/',views.rentcardisplay,name='rentcardisplay'),
    path('display_avail_cars/',views.display_avail_cars,name='display_avail_cars'),
    path('rentcarform/',views.rentcarform,name='rentcarform'),
    # path('bookcabform/',views.bookcabform,name='bookcabform'),
    path('book/(<int:book_id>)',views.book_my_car,name='book_my_car'),
    path('display_req/',views.display_req,name='display_req'),
    path('display_req/(<int:req_id>)',views.accept,name='display_req_accept'),
    path('history/',views.rentalhistory,name='rentalhistory'),
    path('cab_trip/',views.cab_trip,name='cab_trip'),
    path('endcabtrip/(<int:endcab_id>)',views.endcabtrip,name='endcabtrip'),
    path('trial/<int:trial_id>)',views.trial,name='trial'),
    path('car_history/',views.car_view_history,name='car_history'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taxis/urls.py
from django.urls import path
from taxis import views

app_name='taxis'

urlpatterns = [
    path('booktaxi/',views.booktaxi,name='booktaxi'),
    path('avail_taxi/',views.avail_taxi,name='avail_taxi'),
    path('accept_taxi/(<int:accept_id>)',views.accept_taxi,name='accept_taxi'),
    path('your_trip/',views.your_trip,name='your_trip'),
    path('endtrip/(<int:end_id>)',views.endtrip,name='endtrip'),
    # path('all_trips/',views.all_trips,name='all_trips'),
    path('book_driver/',views.book_driver,name='book_driver'),
    path('book_d/(<int:driver_id>)',views.book_d,name='book_d'),
    path('display_map/(<int:map_id>)',views.display_map,name='display_map'),
    path('taxi_view_history/',views.taxi_view_history,name='taxi_view_history'),

]

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>GetCab</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

    <!-- Font Awesome JS -->








    {% block slidecss %}
    {% endblock slidecss %}

    </head>


    <body>

      <!-- <script>

        {% block slidejava %}
        {% endblock slidejava %}
      window.onscroll = function() {myFunction()};

      var header = document.getElementById("content");
      var sticky = header.offsetTop;

      function myFunction() {
        if (window.pageYOffset > sticky) {
          header.classList.add("sticky");
        } else {
          header.classList.remove("sticky");
        }
      }
      </script> -->

            <!-- Page Content  -->
            <div id="content" >

                <nav class="navbar navbar-expand-lg navbar-light bg-dark"     style="font-size: 20px;color: #18a3bf;">
                    <div class="container-fluid">
                      <a class="navbar-brand" style="font-size: 24px;color:#f7f6ed" href="{% url 'accounts:home' %}"><i style="color:#f7f6ed" class="fa fa-car" style="color:white;" aria-hidden="true"></i>
                  Getcab</a>


                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                          <div class="navbar-nav">


                            <!-- <a class="nav-item nav-link" style="color:#f7f6ed;padding-left:200px;" href="{% url 'rentedcars:rentcarform' %}">Rent_Car</a>
                            <a class="nav-item nav-link" style="color:#f7f6ed" href="{% url 'taxis:booktaxi' %}">Book_Rent</a>
                            <a class="nav-item nav-link active" style="color:#f7f6ed" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
                            <a class="nav-item nav-link" style="color:#f7f6ed" href="{% url 'accounts:user_signup' %}">User_SignUp</a> -->
                            <!-- <a class="nav-item nav-link" style="color:#f7f6ed" href="{% url 'emergencycontacts:sendmail' %}">Emergency</a> -->




                          </div>
                        </div>

                            <a class="btn btn-primary" href="{% url 'emergencycontacts:sendmail' %}" role="button" style="background-color:#db5769;">Emergency</a>
                            <a class="btn btn-primary" href="{% url 'notifications:index' %}" role="button" style="background-color:#d9d9d9;"><i class="fa fa-bell" style="color:#18a3bf;"></i></a>
                            <a class="btn btn-primary" href="{% url 'accounts:view_profile' %}" role="button" style="background-color:#d9d9d9;color:#18a3bf;"><i class="fa fa-user" style="color:#18a3bf"></i>{{ request.user }}</a>

                            {% if user.is_authenticated %}
                            <a class="nav-item nav-link" style="color:#f7f6ed" href="{% url 'accounts:user_logout' %}">Logout</a>
                            {% else %}
                            <a class="nav-item nav-link" style="color:#f7f6ed" href="{% url 'accounts:user_login' %}">Login</a>
                            {% endif %}


                    </div>
                </nav>



          </div>

          {% block body_block %}




          {% endblock body_block %}

          <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
          <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>


    </body>

    </html>

templates/taxi_index.html
{% load static %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>GetCab</title>

  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <!-- Our Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/home.css' %}">

  <!-- Font Awesome JS -->
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>









    </head>


    <body>

            <div id="content" >

                <nav class="navbar navbar-expand-lg navbar-light bg-dark" >
                    <div class="container-fluid">
                      <a class="navbar-brand" style="color:#f7f6ed" href="{% url 'accounts:taxi_home' %}"><i style="color:#f7f6ed" class="fa fa-car" style="color:white;" aria-hidden="true"></i>
                  Getcab</a>

                  <form method="POST" action="{% url 'accounts:taxi_home' %}" style="position: absolute;right:100px">
                    {%csrf_token%}
                    {% if t.active == True %}
                      <input type="submit" value="Active" name="active" class="btn btn-info" style="background-color: green">
                      {% else %}
                      <input type="submit" value="Inactive" name="inactive" class="btn btn-info" style="background-color: orangered">
                      {%endif%}
                    </form>
<!--
                    <a class="btn btn-primary" href="{% url 'accounts:view_profile' %}" role="button" style="background-color:#d9d9d9;position: absolute;right:190px"><i class="fa fa-bell" style="color:#18a3bf;"></i></a> -->
                    <a class="btn btn-primary" href="{% url 'accounts:view_profile' %}" role="button" style="background-color:#d9d9d9;color:#18a3bf;position: absolute;right:200px"><i class="fa fa-user" style="color:#18a3bf"></i>{{ request.user }}</a>

                            {% if user.is_authenticated %}
                            <a class="nav-item nav-link" style="color:#f7f6ed" href="{% url 'accounts:user_logout' %}">Logout</a>
                            {% else %}
                            <a class="nav-item nav-link" style="color:#f7f6ed" href="{% url 'accounts:user_login' %}">Login</a>
                            {% endif %}


                    </div>
                </nav>



          </div>

          {% block body_block %}




          {% endblock body_block %}



    </body>

    </html>

templates/taxihome.html
{% extends 'taxi_index.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block slidecss %}
<style>
    *{margin:0px; padding:0px; font-family:Helvetica, Arial, sans-serif;}

    /* Full-width input fields */
    input[type=text]{
        position: center;
        padding: 12px 20px;
        margin: 8px 26px;
        display: inline-block;
        border-radius: 10%;
        border: 1px solid #ccc;
        box-sizing: border-box;
        font-size:16px;
    }
    input[type=number]{
        position: center;
        padding: 12px 20px;
        margin: 8px 26px;
        display: inline-block;
        border-radius: 10%;
        border: 1px solid #ccc;
        box-sizing: border-box;
        font-size:16px;
    }
    .container{
        width: 400px;
    }

    .form{
        background-color: #fefefe;
        margin: 4% auto 15% auto;
        border: 1px solid #888;
        width: 500px;
        padding-bottom: 30px;
    }

    .modal {
        display:none;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0,0,0,0.4);
    }
    .close {
        position: absolute;
        right: 25px;
        top: 0;
        color: #000;
        font-size: 35px;
        font-weight: bold;
    }
    .close:hover,.close:focus {
        color: #57cbcc;
        cursor: pointer;
    }

    /* Add Zoom Animation */
    .animate {
        animation: zoom 0.6s
    }
    @keyframes zoom {
        from {transform: scale(0)}
        to {transform: scale(1)}
    }

    .action {
        background-attachment: fixed;
    }

    .action h2 {
        font-weight: 700;
        color: #dddddd;
    }

    .action p {
        font-size: 16px;
        color: #ffffff;
    }

    .action .btn-main {
        margin-top: 20px;
    }
    .action .btn-main:hover{
        opacity: 0.7;
    }

</style>
{% endblock slidecss %}


<body>

<!-- Page Content  -->
{% block body_block %}

<div style="background-image: url('{% static 'images/taxibg.jpg' %}');background-size:cover;background-repeat:no-repeat;height: 780px;">
</div>
<br><br><br>

<div class="action" style="background-image: url('{% static 'images/taxibg1.jpg' %}');background-size:cover;background-repeat:no-repeat;height: 300px;">
    <div class="col-md-12 text-center">
        <br><br><br>
        <h2>Check Your History</h2>
        <p>with your taxi details open, you can have the best experience of work with us.We ensure easy pickups according to your location</p>
        <a class="btn btn-primary" href="{% url 'taxis:taxi_view_history' %}" role="button">History</a>
        </div>
    </div>


<script>
    // If user clicks anywhere outside of the modal, Modal will close

    var modal = document.getElementById('modal-wrapper');
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCe2otGPKiUf4Qq35MmOfDWHaQm-Cjtopw&libraries=places"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <script>



    var searchBox = new google.maps.places.SearchBox(document.getElementById('mapsearch'));


    </script>








{% endblock body_block %}

</body>